セルフコーディングにチャレンジ。
ryamakuchi/html5-css3-modern-coding pull request #6
Opened 2018-08-07 16:44 UTC by ryamakuchi

* [ ] とりあえずコミットしてから答え合わせする。
* [ ] 答えとおなじ部分、違う部分をメモする。

2018-08-08 08:27 UTC, inouetakuya requested changes
ソースコードを落としてきたけど、見た目バッチリやん！GJ :+1:

コードの品質云々より前に、まずはゴールまで行っていることが大事だと思うので！

そして、これがさらに「グレート」になるにはどうしたら良いか、あたりをいくつかコメントしたので確認してみてくださいー。

2018-08-08 08:27 UTC, inouetakuya commented on my-standard-layout/src/css/style.css
> +  z-index: 2;
> あとなぜかz-indexつけないと、下にかくれちゃうようになってて、原因調べようと思ってました。。（たぶん親要素にdisplay: relative;つけなかったせい‥？）

と Messenger に書いていたけど、

はて？いま、プルリクのブランチを落としてきて、手元で z-index を消してみたけど、下に隠れるようにはなっていないよ？（Chrome 68）

ただ、それはそれとして、`display: absolute` と `display: relative;` の関係はいまの段階でしっかり理解しておいたほうがよさそうですね :smile:

2018-08-08 08:27 UTC, inouetakuya commented on my-standard-layout/src/css/style.css
> +  margin: -10px;
ネガティブマージンは典型的な使いどころがあって、たしかこの本でも出てきたっけな。ただ、それ以外の場合は「素直に」top と left を使っておいたほうが良さそう。

「素直に」と書いたのは、コードを読む人は、通常、position: absolute が出てきたら、合わせて top と left を使うよねと判断するだろうという前提。

「素直」とか「普通はこう書く」みたいなやつは、この本とか、僕とのやり取りのなかで、どんどん積み重ねていきましょうー :muscle:

2018-08-08 08:27 UTC, inouetakuya commented on my-standard-layout/src/css/style.css
> +  width: 200px;
ここにはいくつか改善の余地があって。

* 読み手に 200px の根拠が分かりづらいこと
* 根拠が分かりづらいと、どこかの値を変更したときに、合わせて、この箇所も変更しなければならないケースで下記のことが起こり得る
  * 変更漏れ
  * どう変更したら良いか分からない
  * どう変更したら良いか調べるのに時間がかかる
* また、どこかの値を変更したときに、合わせて、この箇所も自動的に変更が反映されたら、尚良し。最高。

### 梅）コメント

コードだけで伝えるのが難しいときは、コメントで補う。

```css
width: 200px; /* .side-menu の横幅 275px から画像と余白を引いた値 */
```

### 竹）コメント + 計算式

計算式を書いておくと、暗算でミスを起こすのを避けられる。

```css
width: calc(275px - (55px + 20px)); /* .side-menu の横幅から画像と余白を引いた値 */
```

https://caniuse.com/#search=calc は使って良い時代。

### 松）変数で説明＆変更を自動反映

SCSS が使えるなら、という前提だけど、ここは変数の使いどころ。

各値を変数名で示しているので、コメントも不要になる。

```scss
$side-menu-width: 275px;
$ranking-image-width: 55px;
$ranking-image-margin: 20px;

.side-menu {
  width: $side-menu-width;
}

.ranking .text {
  width: calc($side-menu-width - ($ranking-image-width - $ranking-image-margin));
}
```

2018-08-10 16:07 UTC, ryamakuchi commented on my-standard-layout/src/css/style.css
> +  z-index: 2;
* z-indexは何だったのだらう…普通に隠れませんね笑

2018-08-10 16:16 UTC, ryamakuchi commented on my-standard-layout/src/css/style.css
> +  margin: -10px;
### 使い所その①
* 要素を中央に寄せるとき。
> width: 50px; の要素をleft: 50%; で中央に配置したあとに、margin-left: 25px; で真ん中ぴったり✨みたいな。

### 使い所その②
* アンカーの頭出しをしたいとき。
> #hoge みたいにページ内アンカーに飛びたいとき、固定ヘッダー(height: 50px;)があると隠れちゃう。
> そんなときはmargin-top: -50px; padding-top: 50px;で、要素の範囲を少し上まで拡大するとちょうどよくなる。

**この場合は、素直にtop: left: 使います!!👍**

2018-08-10 16:19 UTC, ryamakuchi commented on my-standard-layout/src/css/style.css
> +  width: 200px;
これ最高です。こういうのが知りたかったんです。
おかげでscssの恩恵がすこしわかりました。
↓
次の写経はscssでやる! わいわい!

2018-08-10 16:20 UTC, ryamakuchi commented
よし! 次に進むためにこちらもマージします。

2018-08-10 16:20 UTC, merged