SCSSでビジュアルデザインを見ながらコードを書くための環境構築
ryamakuchi/html5-css3-modern-coding pull request #7
Opened 2018-08-09 16:01 UTC by ryamakuchi

scssでスタンダードレイアウトをコーディングしていくための、環境構築。

### 完了条件
  * [ ] my-standard-layout は削除されずに残されていること
    * 学んだことをコメントで残したりしているため
  * [ ] スタイルを SCSS で書いていけること
  * [ ] SCSS を CSS にコンパイルできること
  * [ ] SCSS を編集して保存すると、自動で CSS にコンパイルが実行されること
  * [ ] SCSS や HTML を編集して保存すると、自動でブラウザがリロードされること
  * [ ] できるだけシンプルな構成で、index.html や scss がまっさらな状態になっていること

2018-08-09 20:38 UTC, inouetakuya requested changes
みたよー！いいじゃん！:+1:

いくつかコメントしたので確認してくださいー 😄

2018-08-09 20:38 UTC, inouetakuya commented on .gitignore
> +src/css/
これを ignore するのはあくまで `my-standard-layout-scss` 配下の話なので、ここに書くのではなく、`my-standard-layout-scss/.gitignore` に書くのが良さそうです。

合わせて、.gitignore を復習しておきましょう。

`my-standard-layout-scss/.gitignore` に

* `src/css/` と書いたときと
* `/src/css` と書いたときと
* `src/css` と書いたときとの違いが説明できるようなっていたら良いと思います。

あと、この `html5-css3-modern-coding/.gitignore` に `src/css/` と書くことでどういうマズいことが起こり得るかが説明できると良いと思います。

2018-08-09 20:38 UTC, inouetakuya commented on my-standard-layout-scss/MEMO.md
> +# Chapter-02
このメモは `my-standard-layout` のものなので、ここでは真っ新にして良いのでは？

2018-08-09 20:38 UTC, inouetakuya commented on .gitignore
> +src/css/
![image](https://user-images.githubusercontent.com/634357/43924095-a46ac5aa-9c5e-11e8-890e-90737e41de56.png)

この赤い印（警告）は、ファイルの末尾に改行を入れてねという意味です。詳細は下記。

* [ソースコードの最後に改行を入れる - かまたま日記3](https://kamatama41.hatenablog.com/entry/2015/09/10/194414)
* [なぜ gcc はファイルの最後に改行がないと警告を出すのか？ - Schi Heil と叫ぶために](http://hiroakiuno.hatenablog.com/entry/20070409/p1)
* [git - No newline at end of file - Stack Overflow](https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file)

2018-08-09 20:38 UTC, inouetakuya commented on my-standard-layout-scss/README.md
> +My Standard LayOut SCSS
細かいけど、LayOut ではなく Layout かなと。

2018-08-09 20:38 UTC, inouetakuya commented on my-standard-layout-scss/package.json
> +    "build:scss:watch": "node-sass --recursive src/scss --output src/css --watch",
build:scss に変更があったときに、こちらにその変更が反映されるように、

```
"build:scss:watch": "yarn run build:scss --watch",
````

とするほうがベターかなと思いました。

2018-08-09 20:38 UTC, inouetakuya commented on my-standard-layout-scss/package.json
> +    "build:scss:watch": "node-sass --recursive src/scss --output src/css --watch",
See also https://github.com/inouetakuya/html5-css3-modern-coding/pull/9/commits/6a0f6d8ed0badde4920ddf875ca0a816e0d3cca8

2018-08-09 21:00 UTC, inouetakuya commented on my-standard-layout-scss/README.md
> +open http://localhost:3001
僕も勘違いしていたのですが、port はデフォルトで 3000 のようです。

Browsersync options
https://browsersync.io/docs/options#option-port

これまで 3000 を他の環境で使っていたから、代わりに 3001 が選ばれていたという...

2018-08-09 22:35 UTC, ryamakuchi commented on .gitignore
> +src/css/
おっと! ぼけてました!!! ルート直下の.gitignoreに書いてしまったら、他のstandard-layoutとかのフォルダ含め全てのsrc/css/が、監視されなくなっちゃう…

> my-standard-layout-scss/.gitignore に
> * src/css/ と書いたときと
> * /src/css と書いたときと
> * src/css と書いたときとの違いが説明できるようなっていたら良いと思います。

> my-standard-layout-scss/.gitignore に
> 1. src/css/ と書いたとき ↓
こうすると、 **サブディレクトリ** 配下のすべてのsrc/css配下のファイルが監視対象から外れる。
( my-standard-layout-scss/src/css配下も、my-standard-layout-scss/src/src/css配下も監視対象から外れる ) 
cssディレクトリ自体は無視されない
> 2. /src/css と書いたとき ↓
コレは、.gitignoreがおいてあるmy-standard-layout-scssの絶対パスになるので、my-standard-layout-scss/src/src/cssとかあったとしたら、無視されない
> 3. src/css と書いたとき ↓
上に書いた1. と似ているけど、これだとcssディレクトリ自体が無視されちゃう

2018-08-09 22:40 UTC, ryamakuchi commented on .gitignore
> +src/css/
はっっ
警告も消しときます--!!

2018-08-09 22:45 UTC, ryamakuchi commented on .gitignore
> +src/css/
今修正しました(・ω・)っ 続きはまたお昼にやります!!

2018-08-09 22:48 UTC, ryamakuchi commented on my-standard-layout-scss/MEMO.md
> +# Chapter-02
中身まっさらにしました👍

2018-08-09 22:53 UTC, ryamakuchi commented on my-standard-layout-scss/README.md
> +My Standard LayOut SCSS
正しい文字を使いましょう委員会ですね! ありがとうございます〜

2018-08-10 02:44 UTC, inouetakuya commented on my-standard-layout-scss/package.json
> +    "build:scss:watch": "node-sass --recursive src/scss --output src/css --watch",
See also [Fix: SCSS を Watch していても、新規に追加した SCSS ファイルがコンパイルされない by inouetakuya · Pull Request #11 · inouetakuya/html5-css3-modern-coding](https://github.com/inouetakuya/html5-css3-modern-coding/pull/11)

2018-08-10 12:18 UTC, ryamakuchi commented on my-standard-layout-scss/package.json
> +    "build:scss:watch": "node-sass --recursive src/scss --output src/css --watch",
ありがとうございます!
(そして、nodemon見ました、ブランチきって別プルリクしときますー)

2018-08-10 12:19 UTC, ryamakuchi commented on my-standard-layout-scss/README.md
> +open http://localhost:3001
なるほどですね。

2018-08-10 12:21 UTC, ryamakuchi commented
@inouetakuya 

まままマージしてもよろしいでしょうか…?

2018-08-10 12:33 UTC, ryamakuchi commented
よし! 隊長どのの環境と見比べて問題なさそうなので、まままマージしちゃいます‥!

2018-08-10 12:33 UTC, inouetakuya commented
見ますー 👀

2018-08-10 12:33 UTC, merged

2018-08-10 12:33 UTC, ryamakuchi commented
あっっっ

タッチの差…

2018-08-10 12:35 UTC, inouetakuya commented on my-standard-layout-scss/package.json
> +    "build:scss:watch": "node-sass --recursive src/scss --output src/css --watch",
あ、別プルリクにするんですね、了解ですー

2018-08-10 12:38 UTC, inouetakuya reviewed
https://github.com/ryamakuchi/html5-css3-modern-coding/pull/7#discussion_r209244154

LGTM でっす！

![2e4b0bad9565b3166e30ac57e9cfce4f](https://user-images.githubusercontent.com/634357/43958229-a25b6814-9ce5-11e8-8010-e01dc2a600e2.png)